"""change cordinate to embedding in unique faces

Revision ID: 7a951721467a
Revises: a32043bc6ca0
Create Date: 2026-01-30 22:07:31.930658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7a951721467a'
down_revision: Union[str, Sequence[str], None] = 'a32043bc6ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_faces', sa.Column('Embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    op.drop_column('unique_faces', 'Coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_faces', sa.Column('Coordinates', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_column('unique_faces', 'Embedding')
    # ### end Alembic commands ###
