"""set vector size to 128

Revision ID: 857b03ce9fec
Revises: 8b9465c934a8
Create Date: 2026-02-01 16:01:57.984286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '857b03ce9fec'
down_revision: Union[str, Sequence[str], None] = '8b9465c934a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unique_faces', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unique_faces', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
