"""add url in unique faces

Revision ID: a32043bc6ca0
Revises: fb4e9996bfae
Create Date: 2026-01-30 18:24:30.841102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32043bc6ca0'
down_revision: Union[str, Sequence[str], None] = 'fb4e9996bfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_faces', sa.Column('Url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_faces', 'Url')
    # ### end Alembic commands ###
